name: CI

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release distributables for ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.13.0
      - name: Checkout the code
        uses: actions/checkout@v2.3.4
      - name: Install node packages
        run: npm install
      - name: Electron Builder
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
